language: cpp
compiler:
  - gcc
before_install:
 - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y
 - echo "deb http://packages.ros.org/ros/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/ros-latest.list
 - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
 - sudo apt-get update -qq
 - sudo apt-get install --only-upgrade -qq base-files
install:
 - sudo apt-get install -qq python-rosdep
 - sudo rosdep init
 - rosdep update
 - rosdep install --from-path ./ --ignore-src --rosdistro $ROSDISTRO
before_script:
 - source /opt/ros/$ROSDISTRO/setup.bash
script:
- mkdir build
- cd build
- >
  cmake ..
  -DCATKIN_BUILD_BINARY_PACKAGE="1"
  -DCMAKE_INSTALL_PREFIX="/opt/ros/$ROSDISTRO"
  -DCMAKE_PREFIX_PATH="/opt/ros/$ROSDISTRO"
- make -j2
- sudo make install -j2
